sources:
  in:
    type: http_server
    address: ${HOST}:${PORT}
    headers:
      - "*"

transforms:
  modify:
    type: remap
    inputs:
      - in
    source: |
      message_json = parse_json!(del(.message))
      request_metadata = .
      . = { "message": message_json, "request_metadata": request_metadata }

  route:
    type: route
    inputs:
      - modify
    route: ${VECTOR_ROUTES:-{"default": "true"}}

  set_route:
    type: remap
    inputs:
      - route
    source: |
      .route = to_string!(if exists(.type) { .type } else { "default" })

sinks:
  console_out:
    type: console
    encoding:
      codec: json
    inputs:
      - set_route

  gcs_out:
    type: gcp_cloud_storage
    inputs:
      - set_route
    bucket: ${GCS_BUCKET_NAME:?the bucket name must be supplied via GCS_BUCKET_NAME env var}
    encoding:
      codec: json
    framing:
      method: newline_delimited
    key_prefix: "{{route}}/year=%Y/month=%m/day=%d/"
    batch:
      max_events: ${GCS_BATCH_MAX_EVENTS:-1000}
      timeout_secs: ${GCS_BATCH_TIMEOUT_SECS:-300}