sources:
  in:
    type: http_server
    address: ${HOST}:${PORT}
    headers:
      - "*"

transforms:
  parse_json:
    type: remap
    inputs:
      - in
    source: |
      .message = parse_json!(.message)
      .source = .message.source

  router:
    type: route
    inputs:
      - parse_json
    route:
      search_arena_logs: '.source == "search-arena"'
      fastchat_logs: '.source == "fastchat"'

  set_route_search_arena:
    type: remap
    inputs:
      - router.search_arena_logs
    source: |
      .route = "search_arena"

  set_route_fastchat:
    type: remap
    inputs:
      - router.fastchat_logs
    source: |
      .route = "fastchat"

  sample:
    type: sample
    inputs:
      - set_route_search_arena
      - set_route_fastchat
    rate: 1

sinks:
  console_out:
    type: console
    encoding:
      codec: json
    inputs:
      - sample

  out:
    type: gcp_cloud_storage
    inputs:
      - set_route_search_arena
      - set_route_fastchat
    bucket: ${GCS_BUCKET_NAME:?the bucket name must be supplied via GCS_BUCKET_NAME env var}
    encoding:
      codec: json
    framing:
      method: newline_delimited
    key_prefix: "{{route}}/year=%Y/month=%m/day=%d/"
    batch:
      max_events: ${GCS_BATCH_MAX_EVENTS:-1000}
      timeout_secs: ${GCS_BATCH_TIMEOUT_SECS:-300}