sources:
  in:
    type: http_server
    address: ${HOST}:${PORT}

transforms:
  modify:
    type: remap
    inputs:
      - in
    source: |
      . = parse_json!(string!(.message))

sinks:
  out:
    inputs:
      - modify
    type: gcp_cloud_storage
    bucket: ${GCS_BUCKET_NAME:?the bucket name must be supplied via GCS_BUCKET_NAME env var}
    encoding:
      codec: json
    framing:
      method: newline_delimited
    key_prefix: year=%Y/month=%m/day=%d
