sources:
  in:
    type: http_server
    address: ${HOST}:${PORT}
    headers:
      - "*"

transforms:
  parse_json:
    type: remap
    inputs:
      - in
    source: |
      .message = parse_json!(.message) # Parses the 'message' field without restructuring

  normalize_logs:
    type: remap
    inputs:
      - parse_json
    source: |
      if exists(.request_id) {
        .log_type = "chat"
      } else {
        .log_type = "arena"
      }

  router:
    type: route
    inputs:
      - normalize_logs
    route:
      arena_logs: '.log_type == "arena"'
      chat_logs: '.log_type == "chat"'

  set_route_arena_logs:
    type: remap
    inputs:
      - router.arena_logs
    source: |
      .route = "arena_logs"

  set_route_chat:
    type: remap
    inputs:
      - router.chat_logs
    source: |
      .route = "chat"

  sample:
    type: sample
    inputs:
      - set_route_arena_logs
      - set_route_chat
    rate: 1

sinks:
  console_out:
    type: console
    encoding:
      codec: json
    inputs:
      - sample

  out:
    type: gcp_cloud_storage
    inputs:
      - set_route_arena_logs
      - set_route_chat
    bucket: ${GCS_BUCKET_NAME:?the bucket name must be supplied via GCS_BUCKET_NAME env var}
    encoding:
      codec: json
    framing:
      method: newline_delimited
    key_prefix: "{{route}}/year=%Y/month=%m/day=%d/"
    batch:
      max_events: ${GCS_BATCH_MAX_EVENTS:-1000}
      timeout_secs: ${GCS_BATCH_TIMEOUT_SECS:-300}