sources:
  in:
    type: http_server
    address: ${HOST}:${PORT}

transforms:
  modify:
    type: remap
    inputs:
      - in
    source: |
      . = parse_json!(string!(.message))
  sample:
    type: sampler
    inputs:
      - modify
    rate: ${SAMPLER_RATE:10}

sinks:
  console_out:
    type: console
    encoding:
      codec: json
    inputs:
      - sample
  out:
    inputs:
      - modify
    type: gcp_cloud_storage
    bucket: ${GCS_BUCKET_NAME:?the bucket name must be supplied via GCS_BUCKET_NAME env var}
    encoding:
      codec: json
    framing:
      method: newline_delimited
    batch:
      timeout_secs: ${GCS_BATCH_TIMEOUT_SECS:300}
    key_prefix: year=%Y/month=%m/day=%d
